services:
  - type: web
    name: mintellect-api
    env: node
    buildCommand: npm install && npm run render-postinstall
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /health
